CREATE TABLE MESSAGE(
	MID 		INT auto_increment primary KEY,
    SENDER 		VARCHAR(15),
    RECEIVER 	VARCHAR(15),
    MESSAGE 	TEXT NOT NULL,
    IS_OPEN 	boolean DEFAULT FALSE,
    SEND_DATE 	TIMESTAMP default NOW(),
    CONSTRAINT FK_SENDER FOREIGN KEY (SENDER) REFERENCES USERS(ID),
	CONSTRAINT FK_RECEIVER FOREIGN KEY (RECEIVER) REFERENCES USERS(ID)
    );
    
    