CREATE TABLE USERS(
	ID VARCHAR(15) PRIMARY KEY,
	PASSWORD VARCHAR(20) NOT NULL,
	PHONE VARCHAR(11),
	NAME VARCHAR(10)
);
ALTER TABLE `sys`.`USERS` 
ADD COLUMN `LEVEL` INT NULL DEFAULT 0 AFTER `NAME`;


 CREATE TABLE BOARD(
 	BID 		INT AUTO_INCREMENT PRIMARY KEY,
 	UID 		VARCHAR(15), -- 작성자 이름
 	BTYPE 		VARCHAR(20), -- 교환, 나눔
 	CATEGORY 	VARCHAR(30), -- 항목별 
 	LOC 		VARCHAR(20), -- 지역 (서울, 구단위로)
     LOC2 		VARCHAR(20), -- 사용자 지정 (세부)
 	TITLE 		VARCHAR(20), -- 제목
 	CONTENT 	TEXT,  -- 내용
 	LIKES 		INT DEFAULT 0, -- 좋아요
 	VIEWS 		INT DEFAULT 0, -- 조회수
 	STATE 		VARCHAR(10), -- 거래 완료
 	IMG			BLOB, -- 이미지
 	TIME_OF_UPLOAD DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 업로드 시각
 	CONSTRAINT FK_UID foreign key (uid) references users(id)
 );

CREATE TABLE LIKES(
	LID INT AUTO_INCREMENT PRIMARY KEY,
	BID INT,
	UID VARCHAR(15),
	ISLIKE BOOLEAN DEFAULT TRUE,
	CONSTRAINT FK_UID_LIKE FOREIGN KEY (UID) REFERENCES USERS(ID),
	CONSTRAINT FK_BID FOREIGN KEY (BID) REFERENCES BOARD(BID)
);

CREATE TABLE MESSAGE(
	MID 		INT auto_increment primary KEY,
    SENDER 		VARCHAR(15),
    RECEIVER 	VARCHAR(15),
    MESSAGE 	TEXT NOT NULL,
    IS_OPEN 	boolean DEFAULT FALSE,
    SEND_DATE 	TIMESTAMP default NOW(),
    CONSTRAINT FK_SENDER FOREIGN KEY (SENDER) REFERENCES USERS(ID),
	CONSTRAINT FK_RECEIVER FOREIGN KEY (RECEIVER) REFERENCES USERS(ID)
);
    